### ISSUE TITLE
Copypaste

### ISSUE THREAD

**Issue by Lisennk** [mpociot/socialite-slack#2]
Its copypaste from 
https://github.com/SocialiteProviders/Slack/

**Comment by mpociot** [comment]
No, it's not.
The SocialiteProviders repository wasn't working for me, because of the way the access token is retrieved.

https://github.com/mpociot/socialite-slack/blob/master/src/Provider.php#L91-L103

**Comment by Lisennk** [comment]
So, why not to create a pull request?
